version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: jcc-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jcc-network

networks:
  jcc-network:
    driver: bridge

volumes:
  postgres_data: 