version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: jcc-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jcc-network

networks:
  jcc-network:
    driver: bridge

volumes:
  postgres_data: 